### PR TITLE
New renew() method, TDD tests, improved integration tests

### PR DESCRIPTION
**Pull request by bbossola**
This pull request contains:
- a refactoring of the unit tests, now written in TDD
- a refactoring of the integration tests, now separated and rebuilt so that they use system properties
- a new renew() method that allows to renew a lock
  Now all locks contain a unique UUID so that it's also impossible to unlock somebody else's lock

### CODE REVIEW

**Comment by abelaska** [comment]
Looks great, thanks!

**Comment by Rajuahmed786** [comment]
Use to vivo

**Comment by Rajuahmed786** [comment]
>open great, thanks!
>

**Comment by Rajuahmed786** [comment]
> open

**Pull request merged**
